#!/bin/sh
PREREQ="udev"
prereqs()
{
 echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/iscsiadm /sbin
copy_exec /usr/sbin/iscsid /sbin
copy_exec /usr/sbin/ibstat /sbin
copy_exec /usr/bin/killall /bin

cp -r /etc/iscsi $DESTDIR/etc/iscsi

for x in crc32c libcrc32c iscsi_tcp libiscsi scsi_transport_iscsi iscsi_ibft ib_iser rdma_cm; do
	manual_add_modules ${x}
done
